config/routes.rb
Rails.application.routes.draw do
  get '/signup', to: 'users#new'
  get '/home', to: 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "static_pages#home"
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_reset, only: [:new,:create,:edit,:update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token, :activation_token, :reset_token

  before_save :email_downcase
  before_create :create_activation_digest

  validates :email, presence: true, length: {maximum: 100},uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :name, presence: true, length: {maximum: 50}
  has_secure_password
  validates :password, presence: true, length: {minimum: 6}, allow_nil: true
  validates :coin, :numericality => { :greater_than_or_equal_to => 0 }

  class << self
    def digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end
    def token
      SecureRandom.urlsafe_base64
    end
  end

  def remember
    self.remember_token=User.token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  def forget
    update_attribute(:remember_digest, nil)
  end
  def activate
    update_columns(activated: true, activated_at: Time.zone.now)
  end

  def authenticated?(attr, token)
    digest=self.send("#{attr}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  def create_reset_digest
    self.reset_token=User.token
    update_columns(reset_digest: User.digest(reset_token), reset_sent_at: Time.zone.now)
  end
  def reset_available_checked?
    reset_sent_at < 2.hour.ago
  end
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end
  def send_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  private
    def email_downcase
      self.email.downcase!
    end
    def create_activation_digest
      self.activation_token=User.token
      self.activation_digest=User.digest(activation_token)
    end
end

app/controllers/account_activations_controller.rb
class AccountActivationsController < ApplicationController
  def edit
    @user=User.find_by(email: params[:email])
    if @user && !@user.activated && @user.authenticated?(:activation, params[:id])
      @user.activate
      login @user
      redirect_to user_path(@user)
    else
      redirect_to root_url
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper

  private
  def logged_in_as_user
    unless logged_in?
      store_location
      redirect_to login_url
    end
  end
end

app/controllers/password_reset_controller.rb
class PasswordResetController < ApplicationController
  before_action :get_user, only: [:edit, :update]
  before_action :valid_user, only: [:edit, :update]
  def new
  end
  def create
    @user=User.find_by(email: params[:password_reset][:email].downcase)
    if @user
      @user.create_reset_digest
      @user.send_reset_email
      render 'user_mailer/password_reset'
    else
      render 'new'
    end
  end
  def edit
  end
  def update
    if params[:user][:password].empty?
      @user.errors.add(:password, "can't be empty")
      render 'edit'
    elsif @user.update(user_info)
      login @user
      @user.update_attribute(:reset_digest, nil)
      redirect_to user_path(@user)
    else
      render 'edit'
    end
  end

  private
  def get_user
    @user=User.find_by(email: params[:email])
  end
  def valid_user
    unless @user && @user.authenticated?(:reset, params[:id]) && !@user.reset_available_checked? && @user.activated
      redirect_to root_url
    end
  end
  def user_info
    params.require(:user).permit(:password,:password_confirmation)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    @user=User.find_by(email: params[:session][:email].downcase)
    if @user&.authenticate(params[:session][:password])
      if params[:session][:remember_me] == '1'
        remember @user
      else
        forget @user
      end
      login @user
      redirect_to user_path(@user)
    else
      render "new"
    end
  end
  def destroy
    logout
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_as_user, only: [:edit,:update,:show]
  before_action :correct_user?, only:[:edit,:update,:show]
  def new
    @user=User.new
  end
  def create
    @user=User.new(user_params)
    @user.coin=0.0
    if @user.save
      @user.send_activation_email
      render 'user_mailer/account_activation'
    else
      render 'new'
    end
  end
  def show
    @user=User.find(params[:id])
  end
  def edit
    @user=User.find(params[:id])
  end
  def update
    @user=User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render 'edit'
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
  def correct_user?
    user=User.find(params[:id])
    unless user && user==current_user
      redirect_to root_url
    end
  end
end

app/helpers/account_activations_helper.rb
module AccountActivationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/password_reset_helper.rb
module PasswordResetHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def logged_in?
    !current_user.nil?
  end
  def login(user)
    session[:user_id]=user.id
  end
  def current_user
    if (user_id = session[:user_id])
      @current_user||=User.find_by(id: user_id)
    elsif(user_id= cookies.signed[user_id])
      user= User.find_by(id: user_id)
      if user&.authenticated?(cookies[:remember_token])
        login user
        @current_user=user
      end
    end
  end

  def logout
    forget current_user
    @current_user=nil
    session[:user_id]=nil
  end
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id]=user.id
    cookies.permanent[:remember_token]=user.remember_token
  end
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end
  def store_location
    session[:url_stored]=request.original_url if request.get?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="bg-light text-center text-white mt-auto">
  <!-- Grid container -->
  <div class="container p-4 pb-0">
    <!-- Section: Social media -->
    <section class="mb-4">
      <!-- Facebook -->
      <a
        class="btn btn-primary btn-floating m-1"
        style="background-color: #3b5998;"
        href="#!"
        role="button"
      ><i class="bi bi-facebook"></i></a>

      <!-- Twitter -->
      <a
        class="btn btn-primary btn-floating m-1"
        style="background-color: #55acee;"
        href="#!"
        role="button"
      ><i class="bi bi-twitter"></i></a>

      <!-- Google -->
      <a
        class="btn btn-primary btn-floating m-1"
        style="background-color: #dd4b39;"
        href="#!"
        role="button"
      ><i class="bi bi-google"></i></a>

      <!-- Instagram -->
      <a
        class="btn btn-primary btn-floating m-1"
        style="background-color: #ac2bac;"
        href="#!"
        role="button"
      ><i class="bi bi-instagram"></i></a>

      <!-- Linkedin -->
      <a
        class="btn btn-primary btn-floating m-1"
        style="background-color: #0082ca;"
        href="#!"
        role="button"
      ><i class="bi bi-linkedin"></i></a>
      <!-- Github -->
      <a
        class="btn btn-primary btn-floating m-1"
        style="background-color: #333333;"
        href="#!"
        role="button"
      ><i class="bi bi-github"></i></a>
    </section>
    <!-- Section: Social media -->
  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    <p class="text-white">© 2022 Copyright: NGUYEN Le Hoang</p>
  </div>
  <!-- Copyright -->
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">E-Shopping</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="/home">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/about">About</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/help">Help</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/contact">Contact</a>
        </li>
      </ul>
      <div class="d-flex">

        <form class="d-flex">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>

        <% if logged_in? %>
          <div class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Dropdown
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href=<%= user_path(current_user)%>>Profile</a></li>
              <li><a class="dropdown-item" href=<%= edit_user_path(current_user)%>>Edit</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><%= button_to "Log out", logout_path,method: :delete , class: "dropdown-item" %></li>

            </ul>
          </div>
        <% else %>
            <a class="nav-link nav-item" href="/login">Login</a>
        <% end %>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EShopping</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="d-flex flex-column min-vh-100">
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
    </div>

    <%= debug(params) if Rails.env.development? %>

    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/password_reset/edit.html.erb
<h1>Reset password</h1>
<div class="row justify-content-center">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: password_reset_path(params[:id])) do |f| %>
      <%= render 'shared/error_messages' , object: f.object%>
      <%= hidden_field_tag :email, @user.email %>
      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
      <%= f.submit "Confirm", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/password_reset/new.html.erb
<h1>Reset password</h1>
<div class="row justify-content-center">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:password_reset, url: password_reset_index_path) do |f| %>
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>
      <%= f.submit "Send to my email", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
<div id="error_explanation">
    <div class="alert alert-danger">
        The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
        <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
    </ul>
</div>
<% end %>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>

app/views/users/edit.html.erb
<h1>Edit</h1>
<div class="row d-flex justify-content-center">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>
      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>
      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
      <%= f.submit 'Submit changes', class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<h1>Sign up</h1>
<div class="row d-flex justify-content-center">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>
      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>
      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
      <%= f.submit 'Create my account', class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<section style="background-color: #9de2ff;">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-8">
        <div class="card" style="border-radius: 15px;">
          <div class="card-body p-4">
            <div class="d-flex text-black">
              <div class="flex-shrink-0">
                <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-profiles/avatar-1.webp"
                     alt="Generic placeholder image" class="img-fluid"
                     style="width: 180px; border-radius: 10px;" />
              </div>
              <div class="flex-grow-1 ms-3">
                <h5 class="mb-1"><%= @user.name %></h5>
                <p class="mb-2 pb-1" style="color: #2b2a2a;">
                  Senior Journalist
                </p>
                <div class="d-flex justify-content-start rounded-3 p-2 mb-2"
                     style="background-color: #efefef;">
                  <div>
                    <p class="small text-muted mb-1">
                      Coin
                    </p>
                    <p class="mb-0"><%= @user.coin %></p>
                  </div>
                  <div class="px-3">
                    <p class="small text-muted mb-1">
                      Followers
                    </p>
                    <p class="mb-0">976</p>
                  </div>
                  <div>
                    <p class="small text-muted mb-1">
                      Rating
                    </p>
                    <p class="mb-0">8.5</p>
                  </div>
                </div>
                <div class="d-flex pt-1">
                  <button type="button" class="btn btn-outline-primary me-1 flex-grow-1">
                    Chat
                  </button>
                  <button type="button" class="btn btn-primary flex-grow-1">
                    Follow
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>